version: '3.8'
services:
  app:
    build: ./docker/app
    container_name: barindpost_app
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - barindpost
    command: >
      apache2-foreground
  db:
    image: mysql:8.0
    container_name: barindpost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: barindpost
      MYSQL_USER: barinduser
      MYSQL_PASSWORD: barindpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dbscript.sql:/docker-entrypoint-initdb.d/dbscript.sql:ro
    networks:
      - barindpost
volumes:
  db_data:
networks:
  barindpost:
    driver: bridge 