<?php

namespace App\Commands;

use App\Database\SqlFile;
use App\Database\Seeds\SampleDataSeeder;
use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

/**
 * Regenerate dbscript.sql from the live (migrated) database.
 *
 *   php spark migrate && php spark schema:dump
 *
 * dbscript.sql is what fresh installs import (Docker's docker-entrypoint-initdb.d,
 * cPanel's phpMyAdmin), so it must keep existing — but as a generated artifact of
 * the migrations, not a second hand-edited source of truth. The dump is every
 * table's SHOW CREATE TABLE (IF NOT EXISTS, AUTO_INCREMENT counters stripped)
 * followed by the sample content from app/Database/Schema/sample_data.sql.
 */
class SchemaDump extends BaseCommand
{
    protected $group       = 'Database';
    protected $name        = 'schema:dump';
    protected $description = 'Regenerate dbscript.sql (schema from the migrated database + sample data).';
    protected $usage       = 'schema:dump [--out path] [--no-data] [--group name]';
    protected $options     = [
        '--out'     => 'Output file (default: ROOTPATH/dbscript.sql)',
        '--no-data' => 'Schema only, without the sample content',
        '--group'   => 'Database group to read from (default: the default group)',
    ];

    public function run(array $params)
    {
        $group = $params['group'] ?? CLI::getOption('group') ?? null;
        $db    = \Config\Database::connect($group ?: null);
        if ($db->DBDriver !== 'MySQLi') {
            CLI::error('schema:dump needs the MySQL connection (driver is ' . $db->DBDriver . ').');

            return EXIT_ERROR;
        }

        $out    = $params['out'] ?? CLI::getOption('out') ?? ROOTPATH . 'dbscript.sql';
        $noData = array_key_exists('no-data', $params) || CLI::getOption('no-data') !== null;

        $tables = array_values(array_filter($db->listTables(), static fn ($t) => $t !== $db->getPrefix() . 'migrations'));
        if ($tables === []) {
            CLI::error('No tables found in ' . $db->getDatabase() . ' — run `php spark migrate` first.');

            return EXIT_ERROR;
        }

        $lines = [
            '-- Barind Post database script — GENERATED by `php spark schema:dump` on ' . date('Y-m-d H:i:s') . '.',
            '-- Do not edit by hand: change the schema with a migration in app/Database/Migrations/,',
            '-- run `php spark migrate`, then regenerate this file. Fresh installs import this file',
            '-- (Docker: docker-entrypoint-initdb.d; cPanel: phpMyAdmin). MySQL 8 / utf8mb4.',
            '',
            'SET NAMES utf8mb4;',
            'SET FOREIGN_KEY_CHECKS = 0;',
            '',
        ];

        foreach ($tables as $table) {
            $row = $db->query('SHOW CREATE TABLE `' . $table . '`')->getRowArray();
            $ddl = $row['Create Table'] ?? null;
            if ($ddl === null) {
                CLI::error("Could not read DDL for {$table}");

                return EXIT_ERROR;
            }
            $ddl = preg_replace('/^CREATE TABLE `/', 'CREATE TABLE IF NOT EXISTS `', $ddl);
            $ddl = preg_replace('/\s+AUTO_INCREMENT=\d+/', '', $ddl);
            $lines[] = $ddl . ';';
            $lines[] = '';
        }

        if (! $noData) {
            $lines[] = '-- ---------------------------------------------------------------------------';
            $lines[] = '-- Sample content (app/Database/Schema/sample_data.sql)';
            $lines[] = '-- ---------------------------------------------------------------------------';
            $lines[] = '';
            foreach (SqlFile::statementsFromFile(SampleDataSeeder::DATA_FILE) as $stmt) {
                $lines[] = $stmt . ';';
                $lines[] = '';
            }
        }

        $lines[] = 'SET FOREIGN_KEY_CHECKS = 1;';
        $lines[] = '';

        if (file_put_contents($out, implode("\n", $lines)) === false) {
            CLI::error('Could not write ' . $out);

            return EXIT_ERROR;
        }

        CLI::write(sprintf('Wrote %s: %d tables%s.', $out, count($tables), $noData ? '' : ' + sample data'), 'green');

        return EXIT_SUCCESS;
    }
}
